version: "3.9"
services:
  postgres:
    # build: postgres
    image: vladyslavhladchenko/luxonis_db
    ports:
      - 5432:5432
  server:
    # build: server
    image: vladyslavhladchenko/luxonis_server
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:8080
    environment:
      - STREAMLIT_SERVER_PORT=8080
      - SPIDER_MAX_RESULTS=500